import apiClient from "../lib/apiClient";

export interface TimeSlotAPI {
  id: string;
  subFieldId: string;
  startTime: string;
  endTime: string;
  date: string;
  basePrice: number;
  finalPrice: number;
  peakHourMultiplier?: number;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface SubFieldInfo {
  id: string;
  name: string;
  fieldId: string;
  fieldType: '5vs5' | '7vs7';
  image?: string;
  pricePerHour?: number;
}

class TimeslotService {
  /**
   * Get sub fields for a specific field
   */
  async getSubFields(fieldId: string): Promise<SubFieldInfo[]> {
    const response = await apiClient.get(`/slots/field/${fieldId}/subfields`);
    return response.data;
  }

  /**
   * Get booking availability for a field on a specific date
   */
  async getBookingAvailability(fieldId: string, date: string): Promise<any[]> {
    const response = await apiClient.get(`/bookings/field/${fieldId}/availability`, {
      params: { date }
    });
    return response.data;
  }


  /**
   * Get pricing rules for a field
   */
  async getPricingRules(fieldId: string): Promise<any> {
    try {
      const response = await apiClient.get(`/pricing-rules/field/${fieldId}`);
      return response.data;
    } catch (error) {
      console.error('Error getting pricing rules:', error);
      return { success: false, data: [] };
    }
  }

  /**
   * Bulk create pricing rules (setup peak hours)
   */
  async bulkCreatePricingRules(fieldId: string, rules: Array<{
    from_hour: number;
    to_hour: number;
    multiplier: number;
  }>): Promise<any> {
    const response = await apiClient.post('/pricing-rules/bulk', {
      field_id: fieldId,
      rules
    });
    return response.data;
  }

  /**
   * Convert date format for API compatibility
   */
  formatDateForAPI(date: Date | string): string {
    if (date instanceof Date) {
      return date.toISOString().split('T')[0];
    }
    return date;
  }

  /**
   * Calculate price with peak hour multiplier
   */
  async calculatePriceForTimeSlot(fieldId: string, startTime: string): Promise<any> {
    try {
      const response = await apiClient.post('/timeslots/calculate-price', {
        fieldId,
        startTime
      });
      return response.data;
    } catch (error) {
      console.error('Error calculating price:', error);
      return { basePrice: 300000, multiplier: 1.0, finalPrice: 300000 };
    }
  }
}

// Import TimeSlot interface from existing types
interface TimeSlot {
  id: string;
  field: string;
  startTime: string;
  endTime: string;
  price: string;
  status: 'available' | 'booked' | 'maintenance';
  customerName?: string;
  customerPhone?: string;
  bookingDate?: string;
  paymentStatus?: 'paid' | 'pending' | 'cancelled';
  description?: string;
  maintenanceReason?: string;
  estimatedCompletion?: string;
  maintenanceStaff?: string;
}

export const timeslotService = new TimeslotService();
export default timeslotService;
